import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/App.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Fuel, Filter } from "lucide-react";
import { SearchForm } from "@/components/search-form";
function App() {
    return (_jsx("div", { className: "min-h-screen bg-gray-50", children: _jsxs("div", { className: "container mx-auto px-4 py-6 md:py-12 max-w-7xl", children: [_jsxs("header", { className: "text-center mb-8 md:mb-12", children: [_jsxs("div", { className: "flex items-center justify-center gap-3 mb-4", children: [_jsx("div", { className: "p-3 bg-blue-600 text-white rounded-full", children: _jsx(Fuel, { className: "h-6 w-6 md:h-8 md:w-8" }) }), _jsx("h1", { className: "text-3xl md:text-4xl lg:text-5xl font-extrabold bg-gradient-to-r from-blue-600 to-green-500 bg-clip-text text-transparent", children: "GasFinder" })] }), _jsx("p", { className: "text-base md:text-lg text-gray-600 max-w-4xl mx-auto px-4", children: "Encuentra de forma sencilla las gasolineras m\u00E1s baratas de Espa\u00F1a. Filtra por provincia y carburante para ahorrar en cada repostaje." })] }), _jsxs(Card, { className: "shadow-lg border-t-4 border-t-blue-600 mb-8", children: [_jsx(CardHeader, { className: "pb-2", children: _jsxs(CardTitle, { className: "text-xl md:text-2xl flex items-center justify-center gap-2 text-gray-800 mt-3", children: [_jsx(Filter, { className: "h-5 w-5 md:h-6 md:w-6" }), _jsx("span", { children: "Buscar Gasolineras" })] }) }), _jsx(CardContent, { className: "px-4 md:px-6", children: _jsx(SearchForm, {}) })] }), _jsxs("footer", { className: "mt-12 md:mt-16 text-center text-xs md:text-sm text-gray-500 px-4", children: [_jsxs("p", { className: "mb-2", children: ["\u00A9 ", new Date().getFullYear(), " GasFinder. Creado para facilitar tu ahorro en combustible."] }), _jsx("p", { children: "Datos proporcionados por el Ministerio para la Transici\u00F3n Ecol\u00F3gica y el Reto Demogr\u00E1fico." })] })] }) }));
}
export default App;
